### ISSUE TITLE
Total read counts for the barcode doesn't match the number of sequences in the fastqs

### ISSUE THREAD

**Issue by merckey** [sdparekh/zUMIs#102]
Hi,
Thank you so much for developing this awesome tool!
I recently came across the example data and found that the total read counts for each barcode in `Example.bc.READcounts.rds` is lower than the number of raw reads in the `barcoderead_HEK.1mio.fq.gz` file.

For example:

```
rc= readRDS("Example.bc.READcounts.rds")
rc %>% filter(RG=="AAATCA") %>% summarize_if(is.numeric,sum)
13934
```

```
zcat barcoderead_HEK.1mio.fq.gz | grep ^AAATCA | wc -l
15986
```
Could you explain why the differences in the 2 files?
Thanks!
Jin

**Comment by cziegenhain** [comment]
Hey Jin,

Glad to hear you are liking zUMIs!
Yes you are absolutely right that this number can differ. It is expected because the first step of zUMIs is filtering reads with too low base-call qualities in the barcode & UMI sequences. 
I guess the default is relatively strict, so if you feel like you are loosing too many reads you can play around with the number of bases & phred scores you want to allow.

Hope that helps,
Christoph

**Comment by merckey** [comment]
Got it!
Thanks a lot!
Jin
