### ISSUE TITLE
Updated AWS image

### ISSUE THREAD

**Issue by adamgayoso** [sdparekh/zUMIs#120]
It seems that the image has not been updated since Sep 2018. Would it be possible to update this with the newest version installed?

Thanks!

**Comment by cziegenhain** [comment]
Hi Adam,

Sorry for that, the AWS is always a bit neglected since i dont personally use it.
The most current zUMIs is now available as `zUMIs2.4.0f-hvm` or `ami-0f949a9d22bd09289` 

For smaller updates that we push it should usually be enough to go into the `~/programs/zUMIs` folder and hit `git pull` so you can keep up to date in existing instances easily too!

I am closing here but feel free to get in touch again.

Best,
Christoph
