### ISSUE TITLE
documentation regarding zUMIs inputs

### ISSUE THREAD

**Issue by sbg-dalibor** [sdparekh/zUMIs#138]
Hello,

i have several question regarding inputs in zUMIs. I see there are 4 input fastq file slots, and in 'protocol specific' setup there are examples with 2,3,4 input files, depending on input protocol(order of files differs between protocols)

I have few question regarding those input fastq files slots:

1. I am interested, if input fastq files should follow some rules, for example, does file order matter, should files be named in some special way or similar (so algorithm can know which file contains what data?).

2.  When i try to run zUMIs with 10x data, i provide input data, where i have paired end reads, but in bottom of resulting yaml file, i get SE layout which, i guess, stands for single end. Is this correct behaviour? 

Here is YAML i am using in this case:

###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project: test_project

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /sbgenomics/workspaces/3cf0c125-2ba6-4ac5-a348-be0ec4d5ae7f/tasks/f094df20-e27d-480a-adf3-9aec37c02487/zumis/zummis_inputs/pbmc_10k_v3_S1_L002_R1_001.fastq.gz
    base_definition:
      - BC(1-16)
      - UMI(17-28)
  file2:
    name: /sbgenomics/workspaces/3cf0c125-2ba6-4ac5-a348-be0ec4d5ae7f/tasks/f094df20-e27d-480a-adf3-9aec37c02487/zumis/zummis_inputs/pbmc_10k_v3_S1_L002_I1_001.fastq.gz
    base_definition:
      - BC(1-8)
  file3:
    name: /sbgenomics/workspaces/3cf0c125-2ba6-4ac5-a348-be0ec4d5ae7f/tasks/f094df20-e27d-480a-adf3-9aec37c02487/zumis/zummis_inputs/pbmc_10k_v3_S1_L002_R2_001.fastq.gz
    base_definition:
      - cDNA(1-91)

#reference genome setup
reference:
  STAR_index: /sbgenomics/workspaces/3cf0c125-2ba6-4ac5-a348-be0ec4d5ae7f/tasks/f094df20-e27d-480a-adf3-9aec37c02487/zumis/star_reference_dir #path to STAR genome index
  GTF_file: /sbgenomics/workspaces/3cf0c125-2ba6-4ac5-a348-be0ec4d5ae7f/tasks/f094df20-e27d-480a-adf3-9aec37c02487/zumis/zummis_inputs/Homo_sapiens.GRCh38.84.gtf #path to gene annotation file in GTF format
  additional_files: ##additional_files #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params:  #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: /sbgenomics/workspaces/3cf0c125-2ba6-4ac5-a348-be0ec4d5ae7f/tasks/f094df20-e27d-480a-adf3-9aec37c02487/zumis #specify the full path to the output directory

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 64
mem_limit: null #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  automatic: yes  #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1   #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 100   #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no  #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes   #can be set to no for exon-only counting.
  downsampling: 0   #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0   #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0   #Hamming distance collapsing of UMI sequences.
  write_ham: no   #If hamming distance collapse of UMI sequences is performed, write out mapping tables & UB corrected bam files.
  velocyto: no   #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes  #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  twoPass: yes  #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes

#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths
samtools_exec: samtools #samtools executable
Rscript_exec: Rscript #Rscript executable
STAR_exec: /opt/STAR-2.5.4b/bin/Linux_x86_64/STAR #STAR executable
pigz_exec: /opt/pigz-2.4/pigz #pigz executable

#below, fqfilter will add a read_layout flag defining SE or PE
zUMIs_directory: /opt/zUMIs/
read_layout: SE

3. I have another question for another 10x dataset(same type of files as in question 2), from 2 lanes(that makes 6 files). To run zUMIs on files from both lanes, should i merge fastq files from both lanes and then run with merged files?

4. I am also confused about 'additional files' input, what kind of files can i provide that way,  how do i let zUMIs know purpose of every additional file?

Thanks in advance,
Dalibor

**Comment by cziegenhain** [comment]
Hi Dalibor,

Thanks for your interest in zUMIs. Sorry that the documentation of our program is a bit spotty, but @sdparekh and me are just developing it on the side next to our actual postdoc projects.

Anyway, here come some answers:

1. The order of your files does not matter in particular. Since you should give the definition of cDNA/BC/UMI to each of the input files, this is all we need to parse everything into neat bam files.

2. When setting the SE / PE flag, we were thinking about wether the actual cDNA reads to be mapped are single-end or paired-end. In the case of 10x, you are of course correct that paired-end sequencing is done but as there is only one cDNA read we consider this a SE mapping task.
Another thing for 10x data (and this is very important so I will add this to the wiki too):
I see you are passing the i7 barcode read as file2 into the analysis. 10x is very special as each individual library gets indexed with a mix of 4 primers. zUMIs is not aware of this yet currently, and hence each cell gets wrongly divided into 4 cell barcodes in the analysis. 
I will work on making this more appropriate.
When you are analysing a single 10x sample per zUMIs call, leaving out the i7 file does not have any  drawbacks.

3. I assume here that you mean Illumina sequencing lanes (as 10x samples are often also called lanes referring to their microfluidic chip design). In that case, yes please just concatenate the fastqs of all the lanes.

4. The additional files arguments refers to the mapping reference. Here, you can insert fasta files against which STAR should also map the reads. Here, we are thinking of eg. ERCCs or transgenes like GFP that may not be part of a user's STAR index.

Hope this helps,
Christoph

**Comment by sbg-dalibor** [comment]
Thanks for all the answers Christoph ,this helps a lot !!

So, regarding answer 2, just to be sure, if my fastq files come from single sample, i can leave out i7 file and run with no problems?

Dalibor

**Comment by cziegenhain** [comment]
Great to hear!
Yes, that is correct you can run without the i7. In fact, since 10xGenomics has a pool of 6 million possible cell barcode sequences, the chances of getting the same one in two samples is relatively low.

Best,
Christoph
