### ISSUE TITLE
What will happen to a read that overlaps with two genes?

### ISSUE THREAD

**Issue by piyushjo15** [sdparekh/zUMIs#178]
Hi,
I am performing some single nuclei RNA-seq analysis. I was using premRNA annotation with cellranger. Upon analysis I realized that cellranger count assigns read to the longest gene. Now I am searching for alternate strategy. Upon reading your description, I think it might be a better approach to use zUMIs. However, I wanted to clarify how a read would be assigned if it falls in a intron of one gene and exon of other. For example if you look at HOXB3 (in GENCODE) it overlaps with HOXB4 and B5. While the exons themselves don't overlap, HOXB3 intron overlaps with HOXB4 exons. So if a read aligns, fully or partially, with HOXB4 exon (for example), would it be assigned solely to HOXB4? What about when the reads falls in intron of both HOXB3 and HOXB4? Would it be discarded as ambigious?

Thanks!

**Comment by cziegenhain** [comment]
Hi,

Thanks for your interest in zUMIs! I think this is a great question, apologies for the lack of documentation on this.
Unlike CellRanger's pre-mRNA reference, we always consider exons and introns separately.
In the backend of zUMIs, we use the featureCounts tool to assign gene identity to reads.
Concretely for your examole that means:
If a read fully or partially overlaps with both an HOXB4 exon and a HOXB5 intron, we reason that the most likely source of this read is the exonic part (HOXB4), ie we always prioritise an assignment to an exon feature. If a read falls equally well (fully) into two features of any quantification (two overlapping exons, two overlapping introns), the read will be discarded as ambiguous. We are actually internally discussing if this is really a good decision or if we should move to fractional counting of these instances.

Now I have not looked at this HOX locus, but if the strands of overlapping features are distinct and your data is strand-specific, you can leverage this for better assignment by setting the strandedness setting in zUMIs. In my experience, this removes a lot of the ambiguous cases.

Hope this explanation helps and let me know if you have further questions,

Christoph

**Comment by piyushjo15** [comment]
Hi Christoph!

Thanks for your explanation. I think zUMIs approach will partially solve my problem. I do have genes in the same strand, hence, overlapping intron reads will be discarded.

**Comment by jakaye** [comment]
Hello, 

I was going over some data that was analyzed with zUMIs 1.0 and ran into this issue. Because the data was generated from single nuclei I analyzed the data allowing for intronic reads to be used. 

With zUMIs reads from Ntrk1 were assigned to Pear1. 

[ENSMUSG00000028073](http://useast.ensembl.org/Mus_musculus/Gene/Summary?db=core;g=ENSMUSG00000028073;r=3:87747890-87824306) is the geneID for Pear1 and the ID corresponds to the location chr3:87,747,890-87,824,306 with in that is Ntrk1, ENSMUSG00000028072 (at chr3:87,778,244-87,795,162).

It just so happens that Pear1 is not very abundant in my data set, and I can see only a few reads associated with the locus on IGV. Also, I know from Allen Brain ISH data that Ntrk1 is expressed in my data. Furthermore, I have analyzed my data with both InDrops and zUMIs. InDrops (which has other problems) assigns reads to Pear1 and Ntrk1 appropriately. Whereas zUMIs analysis does not contain Ntrk1. In zUMIS analyzed data, Pear1 now shows up in the same subset of gabaergic neurons that expressed Ntrk1 in the InDrops aligned data. Thus indicating Ntrk1 has been assigned to Pear1.

Likewise, Hoxa3, 4, and 5 are nested within the larger gene, ENSMUSG00000101298. Subsequently, those Hox genes do not appear in downstream analysis and reads are assigned by zUMIs to the larger gene. 

As mentioned before I analyzed with the first version of zUMIs, perhaps you have updated this issue in 2+?
 
Thanks,
Judith

**Comment by cziegenhain** [comment]
Hi Judith, 
there is an update to this in the making, hopefully on GitHub soon. It seems there was some problems when parsing the annotations when a gene was fully in an intron of another gene.

We are also going to have a user-settable option to allow fractional counting of reads that overlap multiple features on the same strand, there seem to be quite some overlapping transcripts annotated in eg the human genome.
