### ISSUE TITLE
zUMIs-master

### ISSUE THREAD

**Issue by baffiak** [sdparekh/zUMIs#18]
Hi,

In zUMI-master.sh is a mistake, X and A parameters are defined same

X ) isCustomFASTQ=$OPTARG;;
A ) isCustomFASTQ=$OPTARG;;

And another question - is it possible to add option to run star without compressed file? For some reason, on my computer (ubuntu under Windows 10) zcat/gunzip -c commands doesn't work with STAR, so I have to use uncompressed files.

Thanks

**Comment by cziegenhain** [comment]
Thanks for letting us know! @sdparekh has fixed that.
For the second question: Because users are likely to process large files, we want to keep data compressed as much as possible.
You probably need to install the [zutils package](https://packages.ubuntu.com/search?keywords=zutils) in your Ubuntu machine.

Best,
Christoph
