### ISSUE TITLE
detect barcodes and UMIs in FASTQ headers (or BAM input)

### ISSUE THREAD

**Issue by gringer** [sdparekh/zUMIs#193]
I'm trying to reproduce the data analysis of mixed species types from the [Smart-Seq3 paper](https://doi.org/10.1038/s41587-020-0497-0) [[pre-print](https://doi.org/10.1101/817924)], but the [raw data](https://www.ebi.ac.uk/ena/data/view/PRJEB36367) has been uploaded to NCBI in BAM format, so I don't have separate index files available for cellular barcodes and UMIs. From the looks of the results I'm getting from BLAST matches, it seems to be the case that the cDNA is entirely encoded within each 150bp read, i.e. `cDNA(1-150)`, and cellular barcodes and UMIs are identified in the BAM files via the CR ["Cellular barcode sequence bases (uncorrected)"] and RX ["Sequence bases of the unique molecular identifier"] tags.

`samtools fastq` is able to read these CR and RX tags and pass them through to the headers of each sequence via `samtools fastq -T CR,RX`, but I can't see anything in the code that will detect these tags. I notice that the `makeSeqs` function is used in `fqfilter_v2.pl`, but it doesn't used the `$rid` variable which could potentially include the cellular barcode. When the barcode sequences don't exist, zUMIs fails at a later barcode tallying step in the R code, because there are no defined barcode sequences.

**Preferred Solution**
It'd be great if zUMIs could parse CR and RX tags in the header of FASTQ records, or maybe even parse the BAM format without needing intermediate FASTQ generation

**Alternatives I've considered**
1. Create dummy accessory FASTQ files from the header sequences
1. Append CR/RX sequences to FASTQ records
1. Modify the code to add this in (I'm in the process of doing this now...)

**Comment by cziegenhain** [comment]
Hey!

Thanks for using zUMIs. I think there is an easier solution for you in this case, because we uploaded fastq files for the Smart-seq3 paper in ArrayExpress https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-8735/files/ :) 
With those you shouldn't have any headache.

In zUMIs, our concept is to use fastq files as they come out the sequencer, so I don't think we will aim to support BCs and UMIs stored in the header of fastq reads. But I agree that it would be good to have flexibility regarding the tag names in bam files! It's not a feature that I can promise to have implemented soon, but I'll definitely add it to our to do list :+1: 

Best,
Christoph

**Comment by gringer** [comment]
> With those you shouldn't have any headache.

I've found a few things that have given me headaches, so far. These are independent of input files (which has been another big headache):

* The example YAML file in the [protocols.io workflow](https://www.protocols.io/view/smart-seq3-protocol-bcq4ivyw?step=18) specifies a barcode file `/smartseq3/expected_barcodes.txt`, but I can't find that file anywhere. It doesn't seem to be in the ArrayExpress files list, nor in the paper supplementary files, nor in the zUMIs repository.

* The options specified in the paper include `--RemoveNoncanonicalUnannotated`, and the error was unhelpful in working out what was wrong:

`EXITING: FATAL INPUT ERROR: empty value for parameter "RemoveNoncanonicalUnannotated" in input "Command-Line-Initial"
SOLUTION: use non-empty value for this parameter`

* zUMIs edits my YAML file, rather than stopping and reporting errors. This was particularly frustrating when I generated an index with STAR using a later version, and got an odd warning complaining that the STAR version was different from the version used for the index:

`WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.4a....`

* The YAML file generator has a tab for "Optional" values, but some of these are not optional (e.g. BC_filter$num_bases; BC_filter$phred, barcodes$automatic).

* One of the R scripts depends on the `inflection` package, and R warnings about package loading are explicitly disabled in the code.

* Seeing strange code structures also gives me headaches when I try to work out what's going wrong with my inputs, although it's not a show-stopper, and probably wouldn't trip up other people:

`if(... && ($goahead eq "yes") && ($isPass ne "fail"))`

I've got a lot of time to muddle my way through these issues, because if I *can* get zUMIs to work, then it's going to save me weeks of work trying to shoehorn data into another, less open program. I'm much more enthusiastic about using Free Software, because it means I have a reasonable chance of getting things to work when they don't. Other people may not be so lucky, and might give up (without any mention of it) at the first sight of an issue.

**Comment by cziegenhain** [comment]
Hi again,

Sorry to hear that things haven't been as straightforward as hoped! We're always happy for feedback. 

- Cell Barcodes: Please check the wiki description of how the barcode annotations should get formatted: https://github.com/sdparekh/zUMIs/wiki/Barcodes#barcode-annotation. It's just a basic plain text file with one line per barcode.
- Sorry that must be a mistake, the STAR option should probably be `--outFilterIntronMotifs RemoveNoncanonicalUnannotated`
- Which edits did zUMIs make to your YAML file? Ideally only the dependency path should be set if missing and the read layout (SE/PE) appended as detected by the pipeline.
- We recently added the check for the STAR version mismatch because it _can_ be an issue in our experience but doesn't have to be. So in your case I wouldn't worry because it's a minor update.
- Sorry for the confusion with the YAML generator: We moved those settings to 'optional' because they will have a set default value :)
- We often hide startup package messages because they can make the verbose messy. Did you experience a particular issue with inflection that I should be looking into?
- STAR overhang: Please generate the genome index without a concrete overhang. https://github.com/sdparekh/zUMIs/wiki/Usage#preparing-star-index-for-mapping In that way you only need one index for all read lenghts that you might encounter. zUMIs will then ask STAR to make the junction db on the fly with the given read length and GTF file during the run.

Again thanks for your feedback, we're happy for people using zUMIs and aim to make the experience as smooth as can be. Unfortunately it can be hard to actively develop & maintain a program when it's not part of our current jobs. 

Best,
Christoph

**Comment by gringer** [comment]
* Cell barcodes - but I don't know what barcodes to use! They haven't been specified anywhere. Am I expected to "just know" the barcodes that are used for the paper?

* zUMIs edits: when I used the `-c` option, it changed from a specified path to the internal path (there's an existing issue about this).

* Inflection: I had no problem with installing this, once I worked out that I needed to install it. I have *lots* of code suggestions, and the use of `library` instead of `require` when the return value is not used is one of these. A better thing to do would be to use `require` and *do something* if the library doesn't exist (e.g. warn / stop). There are a *lot* of instances where zUMIs continues on after an error, when it really should halt - not having a necessary library is a good example of this.

**Comment by cziegenhain** [comment]
- Cell barcodes for the Smart-seq3 paper are deposited in the sample annotation files ArrayExpress: https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-8735/E-MTAB-8735.processed.2.zip
- YAML file edits: I think that is a conceptual misunderstanding that the wiki should explain more in detail: When using the `-c` flag for conda, zUMIs will always use the dependencies packed in the miniconda environment! Hence it will not use your provided paths to e.g. another STAR version.
- Under installation in the wiki, there is a list of all required packages if you don't use conda! https://github.com/sdparekh/zUMIs/wiki/Installation#r
Actually I'm more than happy for any code suggestions and improvements. Feel free to send pull requests if you want to help contribute, I will usually test them once more before merging.
