### ISSUE TITLE
Understanding zUMI Output

### ISSUE THREAD

**Issue by kerimsecener** [sdparekh/zUMIs#213]
Hey Chris,

I have been running zUMI with default parameters on InDrop datasets and have noticed differences in counts for several genes when mapping & counting was done with zUMI and the same with STARsolo. Briefly, some genes present higher counts in zUMI compared to STARsolo and vice-versa. Upon inspection of the reads with a browser, we can see tonnes of reads present for the genes in question, the resulting counts in the output are extremely low (inspite of a sufficient number of reads)

While, I have read several issues related to this in order to understand how the mapping and counting works, I still can't get my head to wrap around this method.

As an example, I have attached the yaml config file for one of the libraries along with the IGV visualization for one of the gene and the final inex counts (nCounts = 28) for the same gene

<img width="1340" alt="Screenshot 2020-09-15 at 15 25 11" src="https://user-images.githubusercontent.com/54856007/93216487-176e8580-f768-11ea-9c6c-cc0cb69bd497.png">

yaml file: [080_S2.txt](https://github.com/sdparekh/zUMIs/files/5225159/080_S2.txt)

Any help would be appreciated.

Thanks !

Kerim

**Comment by cziegenhain** [comment]
Hi Kerim,

So there are a couple of hints I can give here for you to check:

- the bam file obviously has all the reads for all cells, are the same / the relevant cells detected? (ie there can be reads outside of the counted cells in the zUMIs output file)

- It looks like there seem to be several genes on different strands in the vicinity. In this case i would recommend to use stranded gene assignment (not sure which strand InDrops reads from the top of my head though). It can be that reads get tossed due to being ambiguous otherwise.

In general I would recommend to check in the bam file around this example locus, there should be a status tag (eg. for exon "ES" and you can see the reason for not being counted).

Best,
Christoph

**Comment by kerimsecener** [comment]
Hi Christoph,

Thanks for your suggestions.

Concerning the second point, do you mean to set the `strand = 1 or 2` in the config file? 

Thanks,
Kerim

**Comment by cziegenhain** [comment]
Exactly! 
The values are as follows:  0 = unstranded, 1 = positively stranded, 2 = negatively stranded

**Comment by kerimsecener** [comment]
I have tried to run the same library with both strand = 1 and 2, but looks like this was not the issue here. Also, could not find the ES tag in the bam file.

Do you have another suggestion ?

**Comment by cziegenhain** [comment]
The ES tag should definitely be there and is the most informative thing to look at in your case.
Make sure you are opening the correct bam file, it should say "GeneTagged" in the filename.
(Since you haven't mentioned a specific zUMIs version I'm just going to assume that this is newer than 2.6.0 where tag names have changed a bit)

**Comment by kerimsecener** [comment]
So, I am actually using version 2.0.6 because I had started with that back in the day with my first libraries. Maybe I could install the newest version and try running with that to compare ?

**Comment by cziegenhain** [comment]
absolutely!

**Comment by cziegenhain** [comment]
Feel free to reopen if you need additional help.

**Comment by kerimsecener** [comment]
Hi Chris,

So I've finally managed to run the same file with the latest zUMI version. The results are quite similar, although now I have the ES tags in the BAM files. Indeed, the reads that mapped and counted before in starSOLO and not in zUMIs contain ES:Z:Unassigned_NoFeatures; so I guess this is the reason why they are not counted. Is it possible to play with a parameter in the yaml file to ensure these reads are also taken into account ?

Thanks,

Kerim

**Comment by cziegenhain** [comment]
I could imagine that you either gave a different annotation or that there is an issue with the strandedness setting.

**Comment by kerimsecener** [comment]
By different annotation you mean the GTF file ?

**Comment by cziegenhain** [comment]
yes!
