### ISSUE TITLE
SS3 HCA data

### ISSUE THREAD

**Issue by Radek91** [sdparekh/zUMIs#230]
Hi! 

I would like to reanalyze the HCA data from the SS3 paper using zUMIs. More precisely only the PBMCs using single-end R1 after trimming them at 75bp. As a test I am now trying to map the entire HCA data on a human reference (gencode v34). 

The general zUMIs pipeline seems to run nicely but I am seeing some strange numbers coming out in the log files and I was hoping you could help me understand if everything is working as intended.

**1. The standard output:** 

`[1] "5923 barcodes detected."`
`[1] "121548731 reads were assigned to barcodes that do not correspond to intact cells."`
`[1] "Found 101010 daughter barcodes that can be binned into 5770 parent barcodes."`
`[1] "Binned barcodes correspond to 63526187 reads."`

Does this mean that only 63 million reads are informative ? 

**2. filtered.tagged.Log.progress.out**

While it is mapping, the STAR *.filtered.tagged.Log.progress.out also seem to produce some strange results with only 2.1% to 2.3% mapped reads. Is there anything to worry about ? (Are the data sorted by species with the human last ?). The mapped read length seems strange as well (104.8 bp ?).

```
Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other
Nov 19 23:01:05    121.1     2052258      291     2.1%    104.8     0.5%     0.3%     0.0%     0.0%    97.5%     0.2%
Nov 19 23:02:05    155.7     5232454      291     2.1%    104.6     0.5%     0.3%     0.0%     0.0%    97.5%     0.2%
Nov 19 23:03:05    170.7     8580251      291     2.1%    104.6     0.5%     0.3%     0.0%     0.0%    97.5%     0.2%
Nov 19 23:04:05    181.9    12176543      291     2.1%    104.6     0.5%     0.3%     0.0%     0.0%    97.4%     0.2%
Nov 19 23:05:05    185.1    15477749      291     2.1%    104.6     0.5%     0.3%     0.0%     0.0%    97.4%     0.2%
Nov 19 23:06:06    188.4    18946060      291     2.1%    104.6     0.5%     0.3%     0.0%     0.0%    97.4%     0.2%
Nov 19 23:07:07    191.8    22539745      291     2.1%    104.6     0.5%     0.3%     0.0%     0.0%    97.4%     0.2%
```

In addition, it is not exactly clear to me from the paper how you worked with the multi-species mixing. Did you map on an hybrid reference or successively on human / mice / dog ?

**Infos:**

* I am using zUMIs v2.8.3 without the conda env (-c option).
* No other error is raised.
* Reference genome as been indexed without the GTF.
- `STAR   --runMode genomeGenerate   --runThreadN 30   --genomeDir /home/vincent.hahaut/data_storage/REFERENCES/hsap_ss3/STAR_2.7.1a/   --genomeFastaFiles ../GRCh38.primary_assembly.genome.fa`

Thank you in advance for your answer!

[ss3.config.txt](https://github.com/sdparekh/zUMIs/files/5572134/ss3.config.txt)

**Comment by cziegenhain** [comment]
Hi,

Do I understand you correctly that this is just taking the data with read lenghts as it is, no trimming or shortening has been performed yet?

For the barcode verbose: it means that 121548731 reads did not match any annotated / detected barcode, but 63526187 reads could be "rescued" as they were one hamming distance away from a real barcode. The total number of reads in barcodes can be found in the stats files in the zUMIs_output folder.

In the paper, we mapped to a genome index containing all three references at once. Successive mapping does not deal well enough with conserved sequences. Afterwards, we repeated the mapping of the human cells to are purely human genome to reduce multimapping issues.

The mapping stats you post sounds indeed really strange. Could you upload the `.filtered.tagged.Log.final.out` file? It's usually easier to check from that. The fastq files should not be sorted in any way, just as they were received from the sequencer. Since the sample is mostly comprised of PBMCs, I would expect ~75% unique mapping to the human genome alone.

Can you upload a couple of lines of the unmapped bam file that should get produced so we can take a look that everything is correct there?

Best,
Christoph

**Comment by Radek91** [comment]
Hi Christoph,

1. I used only the raw FASTQ data from ArrayExpress. I didn't do any pre-trimming yet.

2. Hamming distance: this makes sense, thank you!

3. The unmapped reads contain human sequences that should have been mapped (tested with blastn). 

Sorry for the delay but I wanted to try another version of zUMI before answering. It seems that using the latest version of zUMI solved the problem. The mapping percentage according to the progress.log file is now >75%.

Thank you for taking the time to answer !

**Comment by cziegenhain** [comment]
Great that it works!
Just another tip: If you want to trim the reads next, just change your cDNA() range in the yaml file and zUMIs will take care of it.

Best,
C
