### ISSUE TITLE
what's the problem in this screen?

### ISSUE THREAD

**Issue by wajm** [sdparekh/zUMIs#233]
Something wrong this?

![스크린샷 2020-11-24 오후 12 55 05](https://user-images.githubusercontent.com/30439753/100046866-76313900-2e54-11eb-84ad-c095ab64024b.png)

**Comment by cziegenhain** [comment]
Yes there seems to be some issues. 
Please upload your YAML file and your zUMIs_YAMLerror.log file that should have been created by the pipeline.

**Comment by wajm** [comment]
hi,
my yaml and zUMIs_YAMLerror.log
[pt1.zip](https://github.com/sdparekh/zUMIs/files/5588244/pt1.zip)
Thanks.

**Comment by cziegenhain** [comment]
Seems very odd to me.
Have you tried using the conda environment for dependencies? 
What system version are you on? feels a bit like some of the shell commands don't get recognized correctly.
The error log also complains that the path to barcode_file is not founds, please use `~` for disabling options instead of empty strings.

**Comment by wajm** [comment]
I'm on iMac pro (macOS Catalina). All dependencies install using conda.
BD Rhapsody also needs barcode file? I don't know they have barcode like 10X system.

**Comment by cziegenhain** [comment]
zUMIs only works on Linux.

**Comment by wajm** [comment]
oh my god~ Sorry.

**Comment by cziegenhain** [comment]
No problem. I suggest you use docker on your computer to run zUMIs!
