### ISSUE TITLE
Question: Does zUMIs perform any frameshift correction for SPLiT-seq?

### ISSUE THREAD

**Issue by jeremymsimon** [sdparekh/zUMIs#298]
I see you implemented a frameshift correction of barcode sequences for other single-cell platforms many releases ago, but I can't quite tell from your code if this applies to SPLiT-seq reads too. Can you comment on that?

**Comment by cziegenhain** [comment]
Hi,

From my understanding of the SPLiT-seq libraries there is no frameshifting expected, so I have not used the frameshift correction for this protocol before: https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup#combinatorial-indexing

As an example where I have used it: ddSeq/SureCell there is an intentional frameshift to make more base diversity while sequencing https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup#ddseq--surecell-3

Best,
Christoph

**Comment by jeremymsimon** [comment]
Okay good to know. SPLiT-seq certainly doesn't have intentional frameshifts, but I think it can happen at some frequency due to sequencing error. No need to incorporate any fixes for this currently
