### ISSUE TITLE
zUMIs on barcode = 10bp

### ISSUE THREAD

**Issue by yingzhang121** [sdparekh/zUMIs#3]
Hi, Developers,

I currently look for a program that can handle 10x data.  From your biorvix paper, it seems zUMIs has the capacity.  So I downloaded it.

When I tried to run it, I found in the manual it says "-c : Base range for cell/sample barcode in -f Barcode read(e.g. 1-6). Required. For STRT-seq give this as 1-n where n is your first cell barcode(-f) length."

However, the latest 10x chemistry (v2) uses a cell barcode of 10bp. I thought "10" might work for the "-c" option, and submitted my job as:
bash zUMIs/zUMIs-master.sh -f raw_reads/KO_S2_L004_R1_001.fastq -r raw_reads/KO_S2_L004_R2_001.fastq -n ko_l4 -g star_mm10/ -o ./ko -a refdata-cellranger-mm10-1.2.0/genes/genes.gtf -p 24 -s 0 -d 100000 -c 10 -m 16 -l 98

The results were so hard to interpret. For example, I totally have 4 samples, there are mapping results for 3 of them, and one just returned with an empty file. And there is no "promised" "expression" and "stats" results (I have R, pigz, samtools and star all installed). So I repeated the job again. I must say the command seemed to have run for a few hours (normal), but again, 3 out of the 4 samples have some output.  I list the results below, so you can have some idea.
 
$ ls -lthr
total 28G
drwx------. 2 zhan2142 support 4.0K Jul  4 12:40 ko_l4._STARgenome
drwx------. 2 zhan2142 support 4.0K Jul  4 12:43 ko_l4._STARpass1
-rw-r-----. 1 zhan2142 support    0 Jul  4 12:44 ko_l4.SJ.out.tab
-rw-r-----. 1 zhan2142 support  329 Jul  4 12:44 ko_l4.Log.progress.out
-rw-r-----. 1 zhan2142 support 1.8K Jul  4 12:44 ko_l4.Log.final.out
-rw-r-----. 1 zhan2142 support  24K Jul  4 12:44 ko_l4.Log.out
-rw-r-----. 1 zhan2142 support 1.5K Jul  4 12:44 ko_l4.aligned.sorted.bam
drwxr-x---. 5 zhan2142 support 4.0K Jul  4 12:46 zUMIs_output
drwx------. 2 zhan2142 support 4.0K Jul  4 13:37 ko_l5._STARgenome
drwx------. 2 zhan2142 support 4.0K Jul  4 13:46 ko_l5._STARpass1
-rw-r-----. 1 zhan2142 support 4.4M Jul  4 14:00 ko_l5.SJ.out.tab
-rw-r-----. 1 zhan2142 support 2.4K Jul  4 14:00 ko_l5.Log.progress.out
-rw-r-----. 1 zhan2142 support 1.9K Jul  4 14:00 ko_l5.Log.final.out
-rw-r-----. 1 zhan2142 support  24K Jul  4 14:00 ko_l5.Log.out
-rw-r-----. 1 zhan2142 support  11G Jul  4 14:16 ko_l5.aligned.sorted.bam
-rw-r-----. 1 zhan2142 support  15G Jul  4 14:29 ko_l5.barcodelist.filtered.sort.sam

And in the zUMIs_output:
$ ls * zUMIs_output/*
ko_l4.aligned.sorted.bam  ko_l4.Log.progress.out    ko_l5.barcodelist.filtered.sort.sam  ko_l5.Log.progress.out
ko_l4.Log.final.out       ko_l4.SJ.out.tab          ko_l5.Log.final.out                  ko_l5.SJ.out.tab
ko_l4.Log.out             ko_l5.aligned.sorted.bam  ko_l5.Log.out

ko_l4._STARgenome:
exonGeTrInfo.tab  exonInfo.tab  geneInfo.tab  sjdbInfo.txt  sjdbList.fromGTF.out.tab  sjdbList.out.tab  transcriptInfo.tab

ko_l4._STARpass1:
Log.final.out  SJ.out.tab

ko_l5._STARgenome:
exonGeTrInfo.tab  exonInfo.tab  geneInfo.tab  sjdbInfo.txt  sjdbList.fromGTF.out.tab  sjdbList.out.tab  transcriptInfo.tab

ko_l5._STARpass1:
Log.final.out  SJ.out.tab

zUMIs_output:
expression  filtered_fastq  stats

zUMIs_output/expression:

zUMIs_output/filtered_fastq:
ko_l5.barcoderead.filtered.fastq.gz  ko_l5.cdnaread.filtered.fastq.gz

zUMIs_output/stats:

So could you give me some help on understanding my output? And could you check whether "-c 10" is a valid option?

I also used cellranger on the same dataset, basically speaking, I got more cells, and more quantified genes.

Best,
Ying

**Comment by sdparekh** [comment]
Hi Ying,

-c option needs a range with start and the end position of your barcode
bases e.g. 1-10

It is designed this way because usually the reads have cell and molecular
barcode in the same read. I.e. 1-10 is cell and 11-16 as molecular.

Let me know if you have any further questions.

Best,
Swati

On Jul 14, 2017 7:14 PM, "yingzhang121" <notifications@github.com> wrote:

Hi, Developers,

I currently look for a program that can handle 10x data. From your biorvix
paper, it seems zUMIs has the capacity. So I downloaded it.

When I tried to run it, I found in the manual it says "-c : Base range for
cell/sample barcode in -f Barcode read(e.g. 1-6). Required. For STRT-seq
give this as 1-n where n is your first cell barcode(-f) length."

However, the latest 10x chemistry (v2) uses a cell barcode of 10bp. I
thought "10" might work for the "-c" option, and submitted my job as:
bash zUMIs/zUMIs-master.sh -f raw_reads/KO_S2_L004_R1_001.fastq -r
raw_reads/KO_S2_L004_R2_001.fastq -n ko_l4 -g star_mm10/ -o ./ko -a
refdata-cellranger-mm10-1.2.0/genes/genes.gtf -p 24 -s 0 -d 100000 -c 10 -m
16 -l 98

The results were so hard to interpret. For example, I totally have 4
samples, there are mapping results for 3 of them, and one just returned
with an empty file. And there is no "promised" "expression" and "stats"
results (I have R, pigz, samtools and star all installed). So I repeated
the job again. I must say the command seemed to have run for a few hours
(normal), but again, 3 out of the 4 samples have some output. I list the
results below, so you can have some idea.

$ ls -lthr
total 28G
drwx------. 2 zhan2142 support 4.0K Jul 4 12:40 ko_l4._STARgenome
drwx------. 2 zhan2142 support 4.0K Jul 4 12:43 ko_l4._STARpass1
-rw-r-----. 1 zhan2142 support 0 Jul 4 12:44 ko_l4.SJ.out.tab
-rw-r-----. 1 zhan2142 support 329 Jul 4 12:44 ko_l4.Log.progress.out
-rw-r-----. 1 zhan2142 support 1.8K Jul 4 12:44 ko_l4.Log.final.out
-rw-r-----. 1 zhan2142 support 24K Jul 4 12:44 ko_l4.Log.out
-rw-r-----. 1 zhan2142 support 1.5K Jul 4 12:44 ko_l4.aligned.sorted.bam
drwxr-x---. 5 zhan2142 support 4.0K Jul 4 12:46 zUMIs_output
drwx------. 2 zhan2142 support 4.0K Jul 4 13:37 ko_l5._STARgenome
drwx------. 2 zhan2142 support 4.0K Jul 4 13:46 ko_l5._STARpass1
-rw-r-----. 1 zhan2142 support 4.4M Jul 4 14:00 ko_l5.SJ.out.tab
-rw-r-----. 1 zhan2142 support 2.4K Jul 4 14:00 ko_l5.Log.progress.out
-rw-r-----. 1 zhan2142 support 1.9K Jul 4 14:00 ko_l5.Log.final.out
-rw-r-----. 1 zhan2142 support 24K Jul 4 14:00 ko_l5.Log.out
-rw-r-----. 1 zhan2142 support 11G Jul 4 14:16 ko_l5.aligned.sorted.bam
-rw-r-----. 1 zhan2142 support 15G Jul 4 14:29 ko_l5.barcodelist.filtered.
sort.sam

And in the zUMIs_output:
$ ls * zUMIs_output/*
ko_l4.aligned.sorted.bam ko_l4.Log.progress.out
ko_l5.barcodelist.filtered.sort.sam
ko_l5.Log.progress.out
ko_l4.Log.final.out ko_l4.SJ.out.tab ko_l5.Log.final.out ko_l5.SJ.out.tab
ko_l4.Log.out ko_l5.aligned.sorted.bam ko_l5.Log.out

ko_l4._STARgenome:
exonGeTrInfo.tab exonInfo.tab geneInfo.tab sjdbInfo.txt
sjdbList.fromGTF.out.tab sjdbList.out.tab transcriptInfo.tab

ko_l4._STARpass1:
Log.final.out SJ.out.tab

ko_l5._STARgenome:
exonGeTrInfo.tab exonInfo.tab geneInfo.tab sjdbInfo.txt
sjdbList.fromGTF.out.tab sjdbList.out.tab transcriptInfo.tab

ko_l5._STARpass1:
Log.final.out SJ.out.tab

zUMIs_output:
expression filtered_fastq stats

zUMIs_output/expression:

zUMIs_output/filtered_fastq:
ko_l5.barcoderead.filtered.fastq.gz ko_l5.cdnaread.filtered.fastq.gz

zUMIs_output/stats:

So could you give me some help on understanding my output? And could you
check whether "-c 10" is a valid option?

I also used cellranger on the same dataset, basically speaking, I got more
cells, and more quantified genes.

Best,
Ying

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sdparekh/zUMIs/issues/3>, or mute the thread

**Comment by yingzhang121** [comment]
I see. I will give it another try.

**Comment by yingzhang121** [comment]
@sdparekh , I repeated the commands over the weekend. But the output is still hard to interpret, and there is still no quantified expression data and stats generated. I have all the R libraries available. So I guess I will pass this new algorithm anyway.

**Comment by sdparekh** [comment]
Hi Ying, 
Please send me your error messages and `ls -R zUMIs_output`. I would be happy to solve the problem. I am curious to know what the issue is. 
Thank you for using our pipeline.
