### ISSUE TITLE
Error in loadNamespace(x)

### ISSUE THREAD

**Issue by xiaoyuppp** [sdparekh/zUMIs#304]
Hi Team, congrats on the awesome software! I am working on the analysis of a skin single cell sequencing dataset utilizing 10X Genomic. I am having issues with the counting step of the zUMIs pipeline.

I created a virtual environment for R3.6.0 using Conda and “plyranges” was successfully installed. When I activated the virtual environment and tried “library (‘Plyranges’)”, these processes didn't have any problem.
<img width="317" alt="library plyranges" src="https://user-images.githubusercontent.com/100671435/156123615-af2370ad-aec1-43d9-aace-99be65be42b6.png">

But when I actually run zUMIs.sh, the nohup.out file tells me: “Error in loadNamespace(x) : There is no package called 'Plyranges'.” I don't know how to solve this problem. And there are also error messages: “Error in gzfile(file, "rb") : Unable to open the link.” I suspect this problem may be related to the error above.
I was hoping you could help me troubleshoot this issue. Would appreciate any input.

My nohup.output files look like this:
[nohup.out.txt](https://github.com/sdparekh/zUMIs/files/8159584/nohup.out.txt)

yaml file:
[Skin-T-F-1_zUMIs_run.txt](https://github.com/sdparekh/zUMIs/files/8159610/Skin-T-F-1_zUMIs_run.txt)

Some basic information:
<img width="425" alt="basic information" src="https://user-images.githubusercontent.com/100671435/156124413-11e1243d-f569-4a03-aa00-2895998283ee.png">

**Comment by cziegenhain** [comment]
Hi,

Sorry for the slow reply - I missed this post.

Instead of setting up a conda environment yourself, I recommend using the integrated one within zUMIs. 
It could otherwise be a configuration issue of your system depending on which binary "Rscript" you default to.

so, please use the -c flag for the zUMIs integrated miniconda. 
`/data/pxyy/workspace/zUMI/zUMIs/zUMIs.sh -c -y Skin-T-F-1_zUMIs_run.yaml`

Best,
Christoph
