### ISSUE TITLE
zUMIs "inex" all read counts and downsampled read counts the same

### ISSUE THREAD

**Issue by seifudd** [sdparekh/zUMIs#311]
Hi, Thanks for developing zUMIs.

I am looking at the read counts for my barcodes/samples (*.dgecounts.rds). I noticed that the total intron-exon read counts for each barcode/sample is the **same** for **all read counts** and **downsampled read counts**? 

Shouldn't the read counts be **different**? 

The parameter for downsampling in the counting_opts: section of the yml file is set to **downsampling: 0**, which we understand is adaptive downsampling. **Regardless, shouldn't all read counts be more than the downsampled read counts**?

In addition, in *.command_line_output_zummis.txt file we noticed that lots of reads are "assigned to barcodes that do not correspond to intact cells (below)." Do these reads get filtered out completely? If yes, which parameter turns this off in zUMIs?

Filtering...
Fri Mar  4 17:06:28 UTC 2022
[1] "83573273 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Found 311 daughter barcodes that can be binned into 18 parent barcodes."
[1] "Binned barcodes correspond to 38478236 reads."

On another note, **we have a total of 352800215 reads sequenced in my FASTQ file.** However, if I sum the number of reads from our *.BCstats.txt we only get 110422891 reads assigned to barcodes. This only accounts for 31.30% of the total reads. Are the rest of the reads being thrown away? Is there a parameter that can be adjusted to include the rest of the reads? It seems awkward to throw away ~70% of the reads.

Any help would be greatly appreciated.

Thanks, Fayaz

**Comment by sdparekh** [comment]
Please post the full verbose log, the yaml file and descriptive plots generated by zUMIs.

**Comment by seifudd** [comment]
[SRG_RNA_Seq_Lite.zUMIs_config_formated.yaml.txt](https://github.com/sdparekh/zUMIs/files/8389245/SRG_RNA_Seq_Lite.zUMIs_config_formated.yaml.txt)
[SRG_RNA_Seq_Lite.filtered.tagged.Log.final.out.txt](https://github.com/sdparekh/zUMIs/files/8389257/SRG_RNA_Seq_Lite.filtered.tagged.Log.final.out.txt)
[SRG_RNA_Seq_Lite.command_line_output_zummis.txt](https://github.com/sdparekh/zUMIs/files/8389261/SRG_RNA_Seq_Lite.command_line_output_zummis.txt)
[SRG_RNA_Seq_Lite.geneUMIcounts.pdf](https://github.com/sdparekh/zUMIs/files/8389263/SRG_RNA_Seq_Lite.geneUMIcounts.pdf)
[SRG_RNA_Seq_Lite.readspercell.pdf](https://github.com/sdparekh/zUMIs/files/8389265/SRG_RNA_Seq_Lite.readspercell.pdf)
[SRG_RNA_Seq_Lite.features.pdf](https://github.com/sdparekh/zUMIs/files/8389268/SRG_RNA_Seq_Lite.features.pdf)
[SRG_RNA_Seq_Lite.downsampling_thresholds.pdf](https://github.com/sdparekh/zUMIs/files/8389272/SRG_RNA_Seq_Lite.downsampling_thresholds.pdf)

**Comment by cziegenhain** [comment]
Hi,

- Regarding downsampling: the setting you used describes the automatically chosen downsampling depth based on the median reads per sample. From the downsampling_thresholds.pdf plot you can see that only the first sample will have a slight downsampling, since all the other samples are between the red lines they will be unchanged. 
- Reads not assigned to barcodes: These are reads that are not an exact match to the annotation of barcodes you gave. This is determined by sequencing error rates.  You can increase the number of mismatches allowed (default: `BarcodeBinning: 1` means 1 mismatch allowed)  
- Reads that do not occur at all: This is because you have kept the most stringent filtering for base qualities that you want to allow:  (`BC_filter: num_bases: 1, phred: 20`, ie. max 1 base under phred 20) if your sequencing run has low quality scores in the barcode and UMI read portions you could loose that many reads although it is unusual for high quality runs in my experience. You can  crank up the number of allowed bases under the quality cutoff to retain more reads.

Best,
Christoph

**Comment by seifudd** [comment]
Hi Christoph,

Thank you for your response. It was the last bullet point that clarified our concerns.

Thanks again, Fayaz
