### ISSUE TITLE
zUMIs and sci-RNA-seq

### ISSUE THREAD

**Issue by achamess** [sdparekh/zUMIs#33]
Hi. We're using the sci-RNA-seq protocol (Cao 2017)
http://science.sciencemag.org/content/357/6352/661/tab-pdf

I don't see it mentioned as one of the supported protocols but it's conceptually similar. The cell index is a combination of P5 + P7 + RT barcode. 

![screen shot 2018-04-12 at 1 26 32 pm](https://user-images.githubusercontent.com/7445362/38693573-4d76dcd2-3e55-11e8-8958-b83d3c676fe4.png)

The RT Barcode and UMI are in Read 1, while the cDNA is in Read 2. Do you see any reason zUMIs would not be compatible with this protocol? I've been using a custom script I made, but yours is much more streamlined and probably faster.

**Comment by cziegenhain** [comment]
Hey,

yes I have worked with sci-RNA-seq data before too.
Just as you said, since the cell barcode is P5 + P7 + RT barcode, we need to perform a preprocessing step before invoking zUMIs.
I attached the preprocessing script I have used before.

Please use as follows:
`cat3fq.pl R1.fastq.gz I1.fastq.gz I2.fastq.gz Combined_barcodeRead.fq 16`
Where 16 is the number of threads to use for zipping the output file (feel free to adjust)

Then, you can invoke zUMIs:
`zUMIs-master.sh -f Combined_barcodeRead.fq.gz -r R2.fastq.gz -m 1-8 -c 9-48`

Let me know if this works for you!

Best,
Christoph

[cat3fq.pl.gz](https://github.com/sdparekh/zUMIs/files/1904314/cat3fq.pl.gz)

**Comment by achamess** [comment]
@cziegenhain Excellent! thanks for the quick reply. I'm glad you've worked with sci-RNA-seq data before. This script will be super helpful. I'm using nuclei data, and I'm so glad you all considered that in your zUMIs pipeline. 

Another question. I have a mixed species experiment, so I want to produce a 'barnyard' plot. I'll need a custom reference that is both mouse and human genome. How would I implement a multispecies alignment in zUMIs?

**Comment by cziegenhain** [comment]
Hey @achamess, 
did you have the chance to test the script and run the pipeline for your sci-RNA-seq data?

**Comment by cziegenhain** [comment]
Excellent! That sounds very encouraging. 
Maybe you already know but you can just rerun zUMIs at the counting stage with another barcode parameter using `-w Counting`

I'm closing the issue for now, feel free to reopen if you need more assistance.

Thanks for your feedback!

**Comment by achamess** [comment]
Hey. Just wanted to follow up. It worked nicely. Very efficient. Way better than my home-made pipeline. I will use zUMIs for this again in the future. The AWS image was also helpful.

**Comment by cziegenhain** [comment]
Fantastic, thanks for the feedback.
Best, christoph
