### ISSUE TITLE
Error with yaml file

### ISSUE THREAD

**Issue by MartaBenegas** [sdparekh/zUMIs#337]
Hi team!

I've just generated a yaml file using the [shiny app](http://shiny.bio.lmu.de:3838/zUMIs-config/) but it raises an error:
```
root@f810632254f2:/usr/bin/zUMIs-2.9.7# bash zUMIs.sh -y /data/yaml
zUMIs.sh: line 7: curl: command not found
------------- 

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs 

-------------
YAML file has an error. Look at the zUMIs_YAMLerror.log or contact developers.
```
The error log file:
![image](https://user-images.githubusercontent.com/57805802/200859843-39802392-d9d9-4004-9b07-b9e24c3f5162.png)

It's all in NULL, but the files does exist in the path specified in the yaml file:
![image](https://user-images.githubusercontent.com/57805802/200860149-ed80ec83-73ae-4d51-8e24-60ccb88ed010.png)

The yaml file (I've just add .txt at the end so I can upload it on github): 
[yaml.txt](https://github.com/sdparekh/zUMIs/files/9972119/yaml.txt)

**Desktop (please complete the following information):**
```
root@f810632254f2:/data# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
I'm inside a docker image.

**Comment by cziegenhain** [comment]
Hi,

Please set the barcode file path to `~`, that should take care of this error.

Other comments on your YAML file, I am assuming this looks like 10x-ish data

- Use cell barcode & UMI error corrections
- Filtering cutoffs as per this default will discard lots of reads due to the length of barcode and UMI. Consider making more lenient
- 10x data is typically stranded, I recommend then using strand-aware gene assignment

Best,
C

**Comment by cziegenhain** [comment]
Hi,

Sounds like the shared i7 merging step is throwing the error. Could be related to the formatting of the file you give there.
Since this is a single 10x sample you do not need to feed the neuron_1k_v3_S1_L001_I1_001.fastq.gz fastq file.

Best,
Christoph
