### ISSUE TITLE
More info about the conda env and docker image

### ISSUE THREAD

**Issue by royfrancis** [sdparekh/zUMIs#343]
I would like some more info about the conda env when using the `-c` argument. What versions of tools are used? Is there a conda env yaml file, for example? Also, is there a [Dockerfile](https://hub.docker.com/r/chrzie/zumis2) definition?

**Comment by cziegenhain** [comment]
Hi,

I am attaching the YAML file for the conda environment which should have all versions.
Unfortunately haven't updated the Dockerfile in a long time, since the packed conda environment works so well any empty Ubuntu docker should just work with a freshly cloned zUMIs from GitHub!

Best,
Christoph
[zUMIs_conda_export.yaml.txt](https://github.com/sdparekh/zUMIs/files/10342458/zUMIs_conda_export.yaml.txt)

**Comment by royfrancis** [comment]
Thanks!
