### ISSUE TITLE
Barcode and UMI parameters to use with ddSEQ data

### ISSUE THREAD

**Issue by driscolc** [sdparekh/zUMIs#35]
Hello Swati, 

I'm wondering what is the ideal way to specify the barcode and UMI ranges for SureCell library preps used for ddSEQ data. This link (https://teichlab.github.io/scg_lib_structs/SureCell.html) describes the forward/barcode read, where there are three separate barcodes separated by a spacer, followed by the UMI. In this case, should the barcode range include all 3 barcodes (something like 5-55)? 

Also, should we expect the barcodes and UMIs to fall in the exact same bases for all forward reads, or is their placement slightly stochastic? Should that be taken into account when specifying these parameters?

**Comment by cziegenhain** [comment]
Hey,

I think the barcodes are fixed in position. In doubt, I would clarify this with Illumina/BioRad. Unfortunately, their website contains little detailed information on this and I have no experience with SureCell myself.
You could either take the complete barcode range as you suggest, or use the [Split-seq preprocessing script](https://github.com/sdparekh/zUMIs/blob/master/preprocess_splitseq.pl) to extract only the variable bases.

Based on the link you sent I would run as such:

`preprocess_splitseq.pl read1.fq.gz 1-6 22-27 43-59 16 read1 /your/output/dir pigz` 
For more info on what each argument of this script does, check [here](https://github.com/sdparekh/zUMIs/wiki/Combinatorial-Indexing)

Then invoke zUMIs as such:
`zUMIs-master.sh -f read1.barcoderead.preprocess.fastq.gz -c 1-18 -m 22-29`

There was just another poster [using zUMIs with ddSeq/SureCell](https://github.com/sdparekh/zUMIs/issues/34), maybe @greener98103 can give feedback on this too?

Thanks for using zUMIs and we are happy to hear about many users with different library prep protocols sharing their experience!

Best,
Christoph

**Comment by driscolc** [comment]
Hi Christoph,

Thanks for the response! Quick follow-up - in looking at the placement of the spacers in our forward/barcode reads, it looks like their position is roughly the same, but they can shift a few base pairs in either direction. Would zUMIs take this into account if setting a larger barcode range?

Best,
Connor

**Comment by cziegenhain** [comment]
Hey,

Okay interesting. So within the exact same barcode signifying one cell, the location of that sequence in the forward read could change? or is it always consistent within one cell barcode and can vary between barcodes? 

In the first case, the answer would no, this doesnt work well with zUMIs. In the second case you should be fine.

When collapsing reads into barcodes, the default is only to combine exactly matching strings.

Best,
Christoph

**Comment by driscolc** [comment]
Hi Christoph,

A further look shows that the first case you mentioned is true, so I think using ranges for our data would not work. If we can create a list of the unique cell barcodes and a list of unique UMI sequences from our data, could we use that as input in some way?

Thanks,
Connor

**Comment by cziegenhain** [comment]
Hey Connor,

That complicates things unfortunately.
I think in this case it would be best to have a preprocessing script that detects the constant linker sequences in the reads and write out the actual barcode bases. 
Could you provide me with some test data (say 1 million reads) and the list of cell barcodes present in there? 

Thanks,
Christoph

**Comment by driscolc** [comment]
Hi Christoph,

I actually made a mistake, the sequences were in the read headers so my counts were off. It looks like the large majority of cell-specific barcodes are all in the exact same position in the read. For example, of ~35,000 instances of a cell-specific barcode, only ~500 were in the wrong position. I think this should work for our data, sorry about the inconvenience. If you still want to create the preprocessing script I'll send that test data your way. 

Thanks, 
Connor

**Comment by cziegenhain** [comment]
Hey Connor,

Ah great! I guess 1-2% of reads falling out should be acceptable. I'd omit a specific preprocessing then, detecting a sequence is relatively slow and we like to have zUMIs run fast :-)

Let me know if you need further help and how zUMIs works for you.

Best,
Christoph

**Comment by driscolc** [comment]
Thanks for all of your help, Christoph. I'll test the pipeline with updated range parameters and post them here if they work with ddSEQ data.

**Comment by cziegenhain** [comment]
Hey, 

maybe a bit long time since your post, but zUMIs does not properly handle the frameshifted barcode blocks of ddSeq.

https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup#ddseq--surecell-3

Best,

Christoph
