### ISSUE TITLE
Unable to complete the git clone command

### ISSUE THREAD

**Issue by tom-snir** [sdparekh/zUMIs#4]
Hello,

I am trying to do the git clone command in bash on windows 10. It starts fine, downloads for a while and then terminates with the following error:

Cloning into 'zUMIs'...
remote: Counting objects: 232, done.
remote: Compressing objects: 100% (108/108), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

No other data is generated. Any idea what could be the issue here?

Thank you,

Tom.

**Comment by cziegenhain** [comment]
Hi Tom,

thanks for trying out zUMIs.

This sounds like a network problem when transferring the git repository.
According to [StackOverflow](https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning) you could try raising your buffer while cloning:
`git config --global http.postBuffer 1048576000`

If that fails aswell, just download the repository as a zip file:
[Download zUMIs](https://github.com/sdparekh/zUMIs/archive/master.zip)

Note that zUMIs won't work on windows 10, because of dependencies such as STAR.

Let me know if this works for you,

Christoph

**Comment by tom-snir** [comment]
Thanks for the quick response, the download went fine with the added config line. I didn't realize the dependencies required Linux, we'll figure something out. 

Thanks again for the help, good to see that zUMIs is supported well.

Tom.

**Comment by cziegenhain** [comment]
Great that the download works now! 
If you do not have access to a Linux machine, we are working to make a functional copy of zUMIs including all dependencies available as an Amazon Cloud image.
If you would like to try it out, you can already start your own EC2 instance with preinstalled zUMIs in in the US East (N. Virginia) location of Amazon Web Services (AWS).
To do that, simply click on "AMIs" in your AWS console and search for AMI ID "ami-ab4919d0" or "zUMIs-image". Next, click on "Launch" to get going!

We are going to update the Readme soon with more detailed instructions.

Best,
Christoph

**Comment by tom-snir** [comment]
טוב, זה עבד אבל מסתבר שה DEPENDENCIES חייבים לינוקס. התקנתי VM, אבל גם שם
אני מסתבך קצת כי הפקודות של ה DEPENCIES, ספציפית STAR לא עובד.

הם הזכירו שיש להם שרת עם ZUMIS מותקן ב amazon web services אבל כשאני מנסה
לעשות יוזר שם זה מבקש כרטיס אשראי. עוד אופציה זה להריץ את זה על השרת שלנו,
כתבתי מייל נפרד על זה לחגית אני צריך קצת אינפורמציה על השרת בשביל להתחבר.

**Comment by tom-snir** [comment]
I apologize, you were mistakenly sent this email. Please ignore. =)

2017-07-24 10:54 GMT+03:00 Tom Snir <tomsnir@gmail.com>:
