### ISSUE TITLE
Showing gene name instead of Ensembl gene ID with using Ensembl annotaitons?

### ISSUE THREAD

**Issue by ykykyksa** [sdparekh/zUMIs#89]
Hello,

If I use Ensembl genome/annotation files (e.g. GRCm38.fasta/GRCm38.91.gtf) for mapping/counting, the Ensembl gene ids are shown instead of gene names in output files although annotation file itself includes gene names inside. It would be great if you could give me an idea to use gene names in output files, other than using BiomaRt in downstream analysis.

**Comment by cziegenhain** [comment]
Hey,

Sorry I dont think we will ever move to short gene names in order to avoid non-unique names in zUMIs.

You can always use your GTF file to make a gene name mapping:

`cat Homo_sapiens.GRCh38.91.chr.gtf | awk 'BEGIN{IFS="\t"}{if($3~"gene")print $0;}' | cut -f9 | awk 'BEGIN{IFS=";"}{print $2"\t"$6;}' | sed 's/\"//g' | sed 's/\;//g' > genemapping.txt`
