### ISSUE TITLE
Is the phred cutoff for barcodes also applied to the cDNA read?

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#91]
Hey,

I still enjoy using zUMIs. Our last run was a bit overclustered, not too bad but read2 had a few lower quality bases at the end in a larger fraction of the reads. The sequencing quality of read1 was unaffected and way higher than a phred20 cutoff for nearly all reads. I noticed that with standard settings zUMIs included only 251,475,031 of 462,222,869 reads int the mapping stage. When I reduced BC_filter and UMI_filter to phred10 nearly all reads were used for mapping and I ended up with a much better dataset. In figure 1 of your paper it looks as if both barcodes and cDNA get filtered based on a phred score cutoff. But can I set these seperately, or is the one cutoff set for the barcodes used for the cDNA as well?

Also, a sidenote (don't want to open up a new topic for that): the detected cells plot in the stats folder regularly crashes adobe reader because it includes too many individual data points. Might be better to include that in a rasterized format.

Thanks for developing zUMIs and best regards
Max

**Comment by MaxKman** [comment]
Hi Swati,

thanks for the quick reply. Yes, I can probably play around with the number of bases allowed to drop beneath treshold. However, I am still not sure why my reads are filtered in the first place. Here is the fastqc plot from read1. I wouldn't expect ~half of the reads too be filtered due to one base below phred20 when looking at this.

![image](https://user-images.githubusercontent.com/30081989/48547602-55c85e80-e8cb-11e8-8701-5dba9dcb956e.png)

Best Max

**Comment by sdparekh** [comment]
Hi Max,
I made a perl script to simply check the barcode fastq file for the number of reads that would filter for give threshold. It only takes barcode fastq file and checks for the number of bases and phred threshold specified. 

You run it with the following command and you get the number of raw and filtered reads as stdout.

perl fqfilter_check.pl barcoderead.filtered.fastq.gz 1 30 1 30 1-12 13-20
Raw reads: 2484156 
Filtered reads: 2287051 

Since i can not attack a file with .pl extension, i am uploading it as .txt but please save it as a perl script before using.

Let me know if you find different numbers with this script. This would be the quickest check for your issue.

Best,
Swati
[fqfilter_check.txt](https://github.com/sdparekh/zUMIs/files/2585142/fqfilter_check.txt)

**Comment by cziegenhain** [comment]
Hey @MaxKman,

did this solve your question? Let us know if we can help further, if not we will close this issue.

**Comment by MaxKman** [comment]
Thanks for the script this confirmed that it was indeed the barcode quality leading to the filtering. Still a bit odd considering the fastqc results but questions answered!

**Comment by cziegenhain** [comment]
Alright excellent to confirm that its the data itself. If I were you, I would just try to set filtering a bit less stringent, especially since your barcodes are not so short.

Good luck!
